SET IDENTITY_INSERT [EnglishApp].[Word] ON;

BEGIN TRANSACTION;

BEGIN
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (1, 'bread', '/bred/', 1, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (2, 'egg', '/eɡ/', 1, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (3, 'cheese', '/tʃiːz/', 1, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (4, 'rice', '/raɪs/', 1, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (5, 'salad', '/ˈsæləd/', 1, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (6, 'soup', '/suːp/', 1, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (7, 'pasta', '/ˈpɑːstə/', 1, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (8, 'pizza', '/ˈpiːtsə/', 1, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (9, 'cake', '/keɪk/', 1, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (10, 'spaghetti', '/spə´geti/', 1, 1)

        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (11, 'pomegranate', '/ˈpɑːmɪɡrænɪt/', 1, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (12, 'strawberry', '/ˈstrɔːberi/', 1, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (13, 'orange', '/ˈɒrɪndʒ/', 1, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (14, 'pineapple', '/ˈpaɪnæpl/', 1, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (15, 'tangerine', '/ˈtændʒəriːn/', 1, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (16, 'longan', '/ˈlôNGgən/', 1, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (17, 'durian', '/ˈdʊriən/', 1, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (18, 'lychee', '/ˈliːtʃi/', 1, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (19, 'jackfruit', '/ˈdʒækfruːt/', 1, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (20, 'starfruit', '/ˈstɑːrfruːt/', 1, 2)

        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (21, 'dragon fruit', '/ˈdræɡən fruːt/', 1, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (22, 'mangosteen', '/ˈmæŋɡəstiːn/', 1, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (23, 'persimmon', '/pərˈsɪmən/', 1, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (24, 'sapodilla', '/ˌsæpəˈdɪlə/', 1, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (25, 'rambutan', '/ræmˈbuːtn/', 1, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (26, 'honeydew', '/ˈhʌn.i.dʒuː/', 1, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (27, 'cantaloupe', '/ˈkæn.tə.luːp/', 1, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (28, 'grapefruit', '/ˈɡreɪpfruːt/', 1, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (29, 'rhubarb', '/ˈruːbɑːrb/', 1, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (30, 'cranberries', '/ˈkrænberi/', 1, 3)

        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (31, 'cycling', '/ˈsaɪklɪŋ/', 2, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (32, 'gymnastics', '/dʒɪmˈnæstɪks/', 2, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (33, 'tennis', '/ˈtenɪs/', 2, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (34, 'running', '/ˈrʌnɪŋ/', 2, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (35, 'swimming', '/ˈswɪmɪŋ/', 2, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (36, 'riding', '/ˈraɪdɪŋ/', 2, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (37, 'volleyball', '/ˈvɒlibɔːl/', 2, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (38, 'basketball', '/ˈbɑːskɪtbɔːl/', 2, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (39, 'baseball', '/ˈbeɪsbɔːl/', 2, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (40, 'jogging', '/´dʒɔgiη/', 2, 1)

        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (41, 'stadium', '/ˈsteɪdiəm/', 2, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (42, 'scoreboard', '/ˈskɔːbɔːd/', 2, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (43, 'striker', '/ˈstraɪkər/', 2, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (44, 'goalkeeper', '/ˈɡoʊlkiːpər/', 2, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (45, 'equalizer', '/ˈiːkwəlaɪzər/', 2, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (46, 'offside', '/ˌɔːfˈsaɪd/', 2, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (47, 'dive', '/daɪv/', 2, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (48, 'trophy', '/ˈtroʊfi/', 2, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (49, 'defender', '/difendə/', 2, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (50, 'pitch', '/pɪtʃ/ ', 2, 2)

        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (51, 'bungee jumping', '/ˈbʌndʒi dʒʌmpɪŋ/', 2, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (52, 'skateboarding', '/ˈskeɪtbɔːdɪŋ/', 2, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (53, 'surfing', 'ˈsɜːfɪŋ/', 2, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (54, 'synchronized swimming', '/ˈsɪŋkrənaɪzd ˈswɪmɪŋ/', 2, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (55, 'wakeboarding', '/ˈweɪkbɔːrdɪŋ/', 2, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (56, 'windsurfing', '//ˈwɪndsɜːfɪŋ/', 2, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (57, 'tetrathlon', '/teˈtræθlən/', 2, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (58, 'bodyboard', '/ˈbɑː.di.bɔːrd/', 2, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (59, 'triathlon', '/traɪˈæθlɑːn/', 2, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (60, 'wetsuit', '/ˈwet.suːt/', 2, 3)

        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (61, 'mandolin', '/mændəlin/', 3, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (62, 'violin', '/ˌvaɪəˈlɪn/', 3, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (63, 'piano', '/piˈænəʊ/', 3, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (64, 'trombone', '/trɑːmˈboʊn/', 3, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (65, 'clarinet', '/,klæriˈnet/', 3, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (66, 'tambourine', '/,tæmbəˈri:n/', 3, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (67, 'harp', '/hɑːrp/', 3, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (68, 'band', '/bænd/', 3, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (69, 'drums', '/drʌm/', 3, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (70, 'organ', '/ˈɔ:gən/', 3, 1)

        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (71, 'xylophone', '/ˈzaɪləfəʊn/', 3, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (72, 'triangle', '/ˈtraɪæŋɡl/', 3, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (73, 'kettledrum', '/ˈket.əl.drʌm/', 3, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (74, 'bagpipes', '/ˈbæɡpaɪps/', 3, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (75, 'cymbal', '/ˈsɪmbəl/', 3, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (76, 'cello', '/ˈtʃeləʊ/', 3, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (77, 'harmonica', '/hɑːrˈmɑːnɪkə/', 3, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (78, 'national anthem', '/ˈnæʃnəl ˈænθəm/', 3, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (79, 'orchestra', '/ˈɔːrkɪstrə/', 3, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (80, 'symphony', '/ˈsɪmfəni/', 3, 2)

        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (81, 'traditional musical', '/trəˈdɪʃənl mjuːzɪkl/', 3, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (82, 'rock', '/rɔk/', 3, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (83, 'cassette player', '/kəˈset ˈpleɪər/', 3, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (84, 'compact disc', '/kɑːmpækt ˈdɪsk/', 3, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (85, 'flautist', '/ˈflaʊtɪst/', 3, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (86, 'lullaby', '/ˈlʌləbaɪ/', 3, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (87, 'musical', '/ˈmyuzɪkəl/', 3, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (88, 'recording studio', '/rɪˈkɔːrdɪŋ stuːdioʊ/', 3, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (89, 'ukulele', '/ˌjuːkəˈleɪli/', 3, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (90, 'classical music', '/ˈklæsɪklˈmjuːzɪk/', 3, 3)

        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (91, 'bear', '/bɛr/', 4, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (92, 'bird', '/bɜrd/', 4, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (93, 'cat', '/kæt/', 4, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (94, 'chicken', '/ˈʧɪkən/', 4, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (95, 'cow', '/kaʊ/', 4, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (96, 'dog', '/dɔg/', 4, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (97, 'fish', '/fɪʃ/', 4, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (98, 'horse', '/hɔrs/', 4, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (99, 'lion', '/ˈlaɪən/', 4, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (100, 'frog', '/frɔg/', 4, 1)

        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (101, 'elephant', '/ˈelɪfənt/', 4, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (102, 'fox', '/fɑːks/', 4, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (103, 'jaguar', '/ˈdʒæɡjuər/', 4, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (104, 'porcupine', '/ˈpɔːrkjupaɪn/', 4, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (105, 'rhinoceros', '/raɪˈnɒsərəs/', 4, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (106, 'squirrel', '/ˈskwɜːrəl/', 4, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (107, 'chimpanzee', '/tʃɪmpənˈzi/', 4, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (108, 'alligator', '/ˈælɪɡeɪtər/', 4, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (109, 'bat', '/bæt/', 4, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (110, 'deer', '/dɪər/', 4, 2)

        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (111, 'beaver', '/ˈbiːvər/', 4, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (112, 'chipmunk', '/ˈtʃɪpmʌŋk/', 4, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (113, 'wolf', '//wʊlf/ ', 4, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (114, 'swordfish', '/ˈsɔːdfɪʃ/', 4, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (115, 'eel', '/iːl/', 4, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (116, 'penguin', '/ˈpeŋɡwɪn/', 4, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (117, 'walrus', '/ˈwɔːlrəs/', 4, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (118, 'turtle', '/ˈtɜːtl/', 4, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (119, 'whale', '/weɪl/', 4, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (120, 'cobra', '/ˈkoʊbrə/', 4, 3)

        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (121, 'actor', '/‘æktə/', 5, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (122, 'actress', '/‘æktris/', 5, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (123, 'architect', '/‘ɑ:kitekt/', 5, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (124, 'artist', '/‘ɑ:tist/', 5, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (125, 'babysitter', '/‘beibi,sitə/', 5, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (126, 'baker', ' /’beikə/', 5, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (127, 'barber', '/‘bɑ:bə/', 5, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (128, 'cashier', '/kæʃˈɪər/', 5, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (129, 'chef', '/ʃef/', 5, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (130, 'doctor', '/‘dɔktə/', 5, 1)

        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (131, 'businessman', '/’biznismən/', 5, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (132, 'businesswoman', '/‘bizniswumən/', 5, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (133, 'butcher', '/ˈbʊtʃ.ər/', 5, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (134, 'carpenter', '/ˈkɑː.pɪn.tər/', 5, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (135, 'custodian', '/kʌsˈtəʊ.di.ən/', 5, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (136, 'dockworker', '/ˈdɒkwɜːkər/', 5, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (137, 'engineer', '/ˌen.dʒɪˈnɪər/', 5, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (138, 'farmer', '/ˈfɑː.mər/', 5, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (139, 'fireman', '/ˈfaɪə.mən/', 5, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (140, 'fisherman', '/ˈfɪʃ.ə.mən/', 5, 2)

        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (141, 'food–service worker', '/fuːd – ˈsɜː.vɪs ˈwɜː.kər/', 5, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (142, 'garment worker', '/ˈɡɑː.mənt ˈwɜː.kər/', 5, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (143, 'hairdresser', '/ˈheəˌdres.ər/', 5, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (144, 'health–care aide', '/fuːd – ˈsɜː.vɪs ˈwɜː.kər/', 5, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (145, 'customer service representative', '/ˈkʌs.tə.mər ˈsɜː.vɪs ˌrep.rɪˈzen.tə.tɪv:/', 5, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (146, 'computer software engineer', '/kəmˈpjuː.tər ˈsɒft.weər ˌen.dʒɪˈnɪər/', 5, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (147, 'data entry clerk', '/ˈdeɪ.tə ˈen.tri klɑːk/', 5, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (148, 'factory worker', '/ˈfæk.tər.i ˈwɜː.kər/', 5, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (149, 'reporter', '/rɪˈpɔːtər/ ', 5, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (150, 'psychologist', '/saɪˈkɒlədʒɪst/', 5, 3)

        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (151, 'daisy', '/ˈdeɪzi/', 6, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (152, 'rose', '/rəʊz/', 6, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (153, 'iris', '/ˈaɪərɪs/', 6, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (154, 'orchid', '/ˈɔːkɪd/', 6, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (155, 'tulip', '/ˈtjuːlɪp/', 6, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (156, 'poppy', '/ˈpɒpi/', 6, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (157, 'pansy', '/ˈpænzi/', 6, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (158, 'violet', '/ˈvaɪələt/', 6, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (159, 'lilac', '/´lailək/', 6, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (160, 'lily', '/ˈlɪli/', 6, 1)

        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (161, 'narcissus', '/nɑːrˈsɪsəs/', 6, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (162, 'mimosa', '/mɪˈmoʊsə/', 6, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (163, 'sunflower', '/ˈsʌnflaʊər/', 6, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (164, 'cyclamen', '/ˈsaɪkləmən/', 6, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (165, 'carnation', '/kɑːˈneɪʃən/', 6, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (166, 'daffodil', '/ˈdæfədɪl/', 6, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (167, 'hyacinth', '/ˈhaɪ.ə.sɪnθ/', 6, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (168, 'anemone', '/əˈnem.ə.ni/', 6, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (169, 'gladiolus', '/ɡlædiˈoʊləs/', 6, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (170, 'forget-me-not', '/fɚˈɡet.mi.nɑːt/', 6, 2)

        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (171, 'bougainvillea', '/buːɡənˈvɪliə/', 6, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (172, 'buttercup', '/ˈbʌtərkʌp/', 6, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (173, 'cactus flower', '/ˈkæktəs ˈflaʊər/', 6, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (174, 'chrysanthemum', '/krɪˈsænθəməm/', 6, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (175, 'cockscomb', '//ˈkɒkskəʊm/', 6, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (176, 'confederate rose', '/kənˈfedərət roʊz/', 6, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (177, 'flamboyant', '/flæmˈbɔɪənt/', 6, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (178, 'honeysuckle', '//ˈhʌnisʌkl/', 6, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (179, 'morning-glory', ' /ˈmɔːrnɪŋ ˈɡlɔːri/', 6, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (180, 'cherry blossom', '/ˈtʃeri ˈblɑːsəm/', 6, 3)

        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (181, 'jail', '/dʒeɪl/', 7, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (182, 'detective', '/dɪˈtek.tɪv/', 7, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (183, 'suspect', '/səˈspekt/', 7, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (184, 'handcuffs', '/ˈhænd.kʌfs/', 7, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (185, 'badge', '//bædʒ/', 7, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (186, 'police officer', '/pəˈliːs ˈɒf.ɪ.səʳ/', 7, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (187, 'gun', '/gʌn/', 7, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (188, 'holster', '/ˈhəʊl.stəʳ/', 7, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (189, 'nightstick', '/ˈnaɪt.stɪk/', 7, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (190, 'trail', '/treil/', 7, 1)

        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (191, 'judge', '/dʒʌdʒ/', 7, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (192, 'robes', '/rəʊbs/', 7, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (193, 'gavel', '/ˈgæv.əl/', 7, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (194, 'witness', '/ˈwɪt.nəs/', 7, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (195, 'court reporter', '/kɔːt rɪpɔrtər/', 7, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (196, 'transcript', '/ˈtræn.skrɪpt/', 7, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (197, 'bench', '/bentʃ/', 7, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (198, 'jury', '/ˈdʒʊə.ri/', 7, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (199, 'jury box', '/ˈdʒʊə.ri bɒks/', 7, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (200, 'court officer', '/kɔːt ˈɒf.ɪ.səʳ/', 7, 2)

        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (201, 'witness stand', '/ˈwɪt.nəs stænd/', 7, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (202, 'prosecuting attorney', '/ˈprɒs.ɪ.kjuːtɪŋ əˈtɜː.ni/', 7, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (203, 'defense attorney', '/dɪˈfents əˈtɜː.ni/', 7, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (204, 'defendant', '/dɪˈfen.dənt/', 7, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (205, 'fingerprint', '/ˈfɪŋ.gə.prɪnts/', 7, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (206, 'a harsh punishment', '/ə hɑːrʃˈpʌnɪʃmənt/', 7, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (207, 'a suspended sentence', '/ə səˈspendɪdˈsentəns/', 7, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (208, 'a wanted notice', '/əˈwɑːntɪdˈnoʊtɪs/', 7, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (209, 'animal cruelty', '/ˈænɪmlˈkruːəlti/', 7, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (210, 'attempted murder', '/əˈtemptɪdˈmɜːrdər/', 7, 3)

        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (211, 'revenue', '/’revənju:/', 8, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (212, 'treasurer', '/’treʒərə[r]/', 8, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (213, 'depreciation', '/di,pri:∫i’ei∫n/', 8, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (214, 'surplus', '’sə:pləs/', 8, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (215, 'share', '/∫eə[r]/', 8, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (216, 'records', '/’rekɔ:d/', 8, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (217, 'turnover', '/’tɜ:n,əʊvə/', 8, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (218, 'inflation', '/in’flei∫n/', 8, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (219, 'speculation', '/,spekjʊ’lei∫n/', 8, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (220, 'sell', '/sel/', 8, 1)

        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (221, 'speculator', '/’spekjʊleitə[r]/', 8, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (222, 'foreign currency', '/’fɒrən ’kʌrənsi/', 8, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (223, 'billing cost', '/ˈbɪlɪŋ/ /kɒst/', 8, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (224, 'custom barrier', '/’kʌstəmz/  /bæriə[r]/', 8, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (225, 'joint venture', '/dʒɔint/ /’vent∫ə[r]/', 8, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (226, 'earnest money', '/’ɜ:nist/ /’mʌni/', 8, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (227, 'administrative cost', 'əd’ministrətiv/ /kɒst/', 8, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (228, 'price_boom', '/prais/_ /bu:m/', 8, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (229, 'financial policies', '/fai’næn∫l/ /’pɒləsi/', 8, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (230, 'account holder', '/ə’kaʊnt/ /’həʊldə[r]/', 8, 2)

        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (231, 'capital accumulation', '/kæpitl/ /ə,kju:mjʊ’lei∫n/', 8, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (232, 'confiscation', '/,kɒnfi’skei∫n/', 8, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (233, 'holding company', '/’həʊldiη/ /’kʌmpəni/', 8, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (234, 'customs barrier', '/’kʌstəmz/ /bæriə[r]/', 8, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (235, 'regular payment', '/’regjulə[r]/ /’peimənt/', 8, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (236, 'financial year', '/fai’næn∫l/ /jie(r)/', 8, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (237, 'financial policy', '/fai’næn∫l/ /’pɒləsi/', 8, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (238, 'economic cooperation', '/,i:kə’nɒmik/ /koʊˌɑːpəˈreɪʃən/', 8, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (239, 'earnest money', '/’ɜ:nist/ /’mʌni/', 8, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (240, 'certificate import', '/sə’tifikit/ /im´pɔ:t/', 8, 3)

        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (241, 'venus', '/’vi:nɘs/', 9, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (242, 'comet', '/’kɒmɪt/', 9, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (243, 'mercury', '/’mɜ:kjɘri/', 9, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (244, 'earth', '/ɜ:θ/', 9, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (245, 'pluto', '/’plu:tɘʊ/', 9, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (246, 'saturn', '/’sætɘn/', 9, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (247, 'asteroid', '/’æstərɔɪd/', 9, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (248, 'mars', '/mɑ:z/', 9, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (249, 'neptune', '/’neptju:n/', 9, 1)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (250, 'star', '/stɑ:/', 9, 1)

        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (251, 'uranus', '/’jʊɘrɘnɘs/', 9, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (252, 'jupiter', '/’dʒu:pɪtɘr/', 9, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (253, 'milky way', '/’milki wei/', 9, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (254, 'constellation', '/,kɔnstə’leiʃn/', 9, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (255, 'unidentified flying objects (UFOs)', '/’ʌnai’dentifaid ´flaiiη ‘ɔbdʤikt/', 9, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (256, 'solar eclipse', '/ˈsəʊ.ləʳ ɪˈklɪps/', 9, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (257, 'lunar eclipse', '/ˈluː.nəʳ ɪˈklɪps/', 9, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (258, 'atmospheric', '/,ætməs’ferik/', 9, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (259, 'gravitational', '/¸grævi´teiʃənəl/', 9, 2)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (260, 'hypothesis', '/haɪˈpɒθɪ̈sɪs/', 9, 2)

        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (261, 'intergalactic', '/¸intəgə´læktik/', 9, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (262, 'prerequisite', '/pri:´rekwizit/', 9, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (263, 'radioactive', '/¸reidiou´æktiv/', 9, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (264, 'spectroscopy', '/spek’trɔskəpi/', 9, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (265, 'superficial', '/ˌsupərˈfɪʃəl/', 9, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (266, 'telescope', ' /’teliskəʊp/', 9, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (267, 'transmutation', '/¸trænzmju:´teiʃən/', 9, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (268, 'vacuum', '/’vækjuəm/', 9, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (269, 'satellite', '/‘sætəlait/', 9, 3)
        INSERT INTO [EnglishApp].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (270, 'microscope ', '/ˈmaɪkrəˌskoʊp/', 9, 3)

END
GO

COMMIT TRANSACTION;

SET IDENTITY_INSERT [EnglishApp].[Word] OFF;