SET IDENTITY_INSERT [EnglishApp1].[Word] ON;

BEGIN TRANSACTION;

BEGIN
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (1, 'bread', N'/bred/', 1, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (2, 'egg', N'/eɡ/', 1, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (3, 'cheese', N'/tʃiːz/', 1, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (4, 'rice', N'/raɪs/', 1, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (5, 'salad', N'/ˈsæləd/', 1, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (6, 'soup', N'/suːp/', 1, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (7, 'pasta', N'/ˈpɑːstə/', 1, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (8, 'pizza', N'/ˈpiːtsə/', 1, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (9, 'cake', N'/keɪk/', 1, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (10, 'spaghetti', N'/spə´geti/', 1, 1)

        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (11, 'pomegranate', N'/ˈpɑːmɪɡrænɪt/', 1, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (12, 'strawberry', N'/ˈstrɔːberi/', 1, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (13, 'orange', N'/ˈɒrɪndʒ/', 1, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (14, 'pineapple', N'/ˈpaɪnæpl/', 1, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (15, 'tangerine', N'/ˈtændʒəriːn/', 1, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (16, 'longan', N'/ˈlôNGgən/', 1, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (17, 'durian', N'/ˈdʊriən/', 1, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (18, 'lychee', N'/ˈliːtʃi/', 1, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (19, 'jackfruit', N'/ˈdʒækfruːt/', 1, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (20, 'starfruit', N'/ˈstɑːrfruːt/', 1, 2)

        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (21, 'dragon fruit', N'/ˈdræɡən fruːt/', 1, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (22, 'mangosteen', N'/ˈmæŋɡəstiːn/', 1, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (23, 'persimmon', N'/pərˈsɪmən/', 1, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (24, 'sapodilla', N'/ˌsæpəˈdɪlə/', 1, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (25, 'rambutan', N'/ræmˈbuːtn/', 1, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (26, 'honeydew', N'/ˈhʌn.i.dʒuː/', 1, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (27, 'cantaloupe', N'/ˈkæn.tə.luːp/', 1, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (28, 'grapefruit', N'/ˈɡreɪpfruːt/', 1, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (29, 'rhubarb', N'/ˈruːbɑːrb/', 1, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (30, 'cranberries', N'/ˈkrænberi/', 1, 3)

        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (31, 'cycling', N'/ˈsaɪklɪŋ/', 2, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (32, 'gymnastics', N'/dʒɪmˈnæstɪks/', 2, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (33, 'tennis', N'/ˈtenɪs/', 2, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (34, 'running', N'/ˈrʌnɪŋ/', 2, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (35, 'swimming', N'/ˈswɪmɪŋ/', 2, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (36, 'riding', N'/ˈraɪdɪŋ/', 2, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (37, 'volleyball', N'/ˈvɒlibɔːl/', 2, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (38, 'basketball', N'/ˈbɑːskɪtbɔːl/', 2, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (39, 'baseball', N'/ˈbeɪsbɔːl/', 2, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (40, 'jogging', N'/´dʒɔgiη/', 2, 1)

        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (41, 'stadium', N'/ˈsteɪdiəm/', 2, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (42, 'scoreboard', N'/ˈskɔːbɔːd/', 2, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (43, 'striker', N'/ˈstraɪkər/', 2, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (44, 'goalkeeper', N'/ˈɡoʊlkiːpər/', 2, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (45, 'equalizer', N'/ˈiːkwəlaɪzər/', 2, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (46, 'offside', N'/ˌɔːfˈsaɪd/', 2, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (47, 'dive', N'/daɪv/', 2, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (48, 'trophy', N'/ˈtroʊfi/', 2, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (49, 'defender', N'/difendə/', 2, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (50, 'pitch', N'/pɪtʃ/ ', 2, 2)

        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (51, 'bungee jumping', N'/ˈbʌndʒi dʒʌmpɪŋ/', 2, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (52, 'skateboarding', N'/ˈskeɪtbɔːdɪŋ/', 2, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (53, 'surfing', N'ˈsɜːfɪŋ/', 2, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (54, 'synchronized swimming', N'/ˈsɪŋkrənaɪzd ˈswɪmɪŋ/', 2, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (55, 'wakeboarding', N'/ˈweɪkbɔːrdɪŋ/', 2, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (56, 'windsurfing', N'//ˈwɪndsɜːfɪŋ/', 2, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (57, 'tetrathlon', N'/teˈtræθlən/', 2, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (58, 'bodyboard', N'/ˈbɑː.di.bɔːrd/', 2, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (59, 'triathlon', N'/traɪˈæθlɑːn/', 2, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (60, 'wetsuit', N'/ˈwet.suːt/', 2, 3)

        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (61, 'mandolin', N'/mændəlin/', 3, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (62, 'violin', N'/ˌvaɪəˈlɪn/', 3, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (63, 'piano', N'/piˈænəʊ/', 3, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (64, 'trombone', N'/trɑːmˈboʊn/', 3, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (65, 'clarinet', N'/,klæriˈnet/', 3, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (66, 'tambourine', N'/,tæmbəˈri:n/', 3, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (67, 'harp', N'/hɑːrp/', 3, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (68, 'band', N'/bænd/', 3, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (69, 'drums', N'/drʌm/', 3, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (70, 'organ', N'/ˈɔ:gən/', 3, 1)

        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (71, 'xylophone', N'/ˈzaɪləfəʊn/', 3, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (72, 'triangle', N'/ˈtraɪæŋɡl/', 3, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (73, 'kettledrum', N'/ˈket.əl.drʌm/', 3, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (74, 'bagpipes', N'/ˈbæɡpaɪps/', 3, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (75, 'cymbal', N'/ˈsɪmbəl/', 3, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (76, 'cello', N'/ˈtʃeləʊ/', 3, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (77, 'harmonica', N'/hɑːrˈmɑːnɪkə/', 3, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (78, 'national anthem', N'/ˈnæʃnəl ˈænθəm/', 3, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (79, 'orchestra', N'/ˈɔːrkɪstrə/', 3, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (80, 'symphony', N'/ˈsɪmfəni/', 3, 2)

        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (81, 'traditional musical', N'/trəˈdɪʃənl mjuːzɪkl/', 3, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (82, 'rock', N'/rɔk/', 3, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (83, 'cassette player', N'/kəˈset ˈpleɪər/', 3, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (84, 'compact disc', N'/kɑːmpækt ˈdɪsk/', 3, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (85, 'flautist', N'/ˈflaʊtɪst/', 3, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (86, 'lullaby', N'/ˈlʌləbaɪ/', 3, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (87, 'musical', N'/ˈmyuzɪkəl/', 3, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (88, 'recording studio', N'/rɪˈkɔːrdɪŋ stuːdioʊ/', 3, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (89, 'ukulele', N'/ˌjuːkəˈleɪli/', 3, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (90, 'classical music', N'/ˈklæsɪklˈmjuːzɪk/', 3, 3)

        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (91, 'bear', N'/bɛr/', 4, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (92, 'bird', N'/bɜrd/', 4, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (93, 'cat', N'/kæt/', 4, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (94, 'chicken', N'/ˈʧɪkən/', 4, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (95, 'cow', N'/kaʊ/', 4, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (96, 'dog', N'/dɔg/', 4, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (97, 'fish', N'/fɪʃ/', 4, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (98, 'horse', N'/hɔrs/', 4, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (99, 'lion', N'/ˈlaɪən/', 4, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (100, 'frog', N'/frɔg/', 4, 1)

        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (101, 'elephant', N'/ˈelɪfənt/', 4, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (102, 'fox', N'/fɑːks/', 4, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (103, 'jaguar', N'/ˈdʒæɡjuər/', 4, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (104, 'porcupine', N'/ˈpɔːrkjupaɪn/', 4, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (105, 'rhinoceros', N'/raɪˈnɒsərəs/', 4, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (106, 'squirrel', N'/ˈskwɜːrəl/', 4, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (107, 'chimpanzee', N'/tʃɪmpənˈzi/', 4, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (108, 'alligator', N'/ˈælɪɡeɪtər/', 4, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (109, 'bat', N'/bæt/', 4, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (110, 'deer', N'/dɪər/', 4, 2)

        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (111, 'beaver', N'/ˈbiːvər/', 4, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (112, 'chipmunk', N'/ˈtʃɪpmʌŋk/', 4, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (113, 'wolf', N'/wʊlf/ ', 4, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (114, 'swordfish', N'/ˈsɔːdfɪʃ/', 4, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (115, 'eel', N'/iːl/', 4, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (116, 'penguin', N'/ˈpeŋɡwɪn/', 4, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (117, 'walrus', N'/ˈwɔːlrəs/', 4, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (118, 'turtle', N'/ˈtɜːtl/', 4, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (119, 'whale', N'/weɪl/', 4, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (120, 'cobra', N'/ˈkoʊbrə/', 4, 3)

        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (121, 'actor', N'/‘æktə/', 5, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (122, 'actress', N'/‘æktris/', 5, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (123, 'architect', N'/‘ɑ:kitekt/', 5, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (124, 'artist', N'/‘ɑ:tist/', 5, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (125, 'babysitter', N'/‘beibi,sitə/', 5, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (126, 'baker', N' /’beikə/', 5, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (127, 'barber', N'/‘bɑ:bə/', 5, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (128, 'cashier', N'/kæʃˈɪər/', 5, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (129, 'chef', N'/ʃef/', 5, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (130, 'doctor', N'/‘dɔktə/', 5, 1)

        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (131, 'businessman', N'/’biznismən/', 5, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (132, 'businesswoman', N'/‘bizniswumən/', 5, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (133, 'butcher', N'/ˈbʊtʃ.ər/', 5, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (134, 'carpenter', N'/ˈkɑː.pɪn.tər/', 5, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (135, 'custodian', N'/kʌsˈtəʊ.di.ən/', 5, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (136, 'dockworker', N'/ˈdɒkwɜːkər/', 5, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (137, 'engineer', N'/ˌen.dʒɪˈnɪər/', 5, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (138, 'farmer', N'/ˈfɑː.mər/', 5, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (139, 'fireman', N'/ˈfaɪə.mən/', 5, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (140, 'fisherman', N'/ˈfɪʃ.ə.mən/', 5, 2)

        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (141, 'food–service worker', N'/fuːd – ˈsɜː.vɪs ˈwɜː.kər/', 5, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (142, 'garment worker', N'/ˈɡɑː.mənt ˈwɜː.kər/', 5, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (143, 'hairdresser', N'/ˈheəˌdres.ər/', 5, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (144, 'health–care aide', N'/fuːd – ˈsɜː.vɪs ˈwɜː.kər/', 5, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (145, 'customer service representative', N'/ˈkʌs.tə.mər ˈsɜː.vɪs ˌrep.rɪˈzen.tə.tɪv:/', 5, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (146, 'computer software engineer', N'/kəmˈpjuː.tər ˈsɒft.weər ˌen.dʒɪˈnɪər/', 5, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (147, 'data entry clerk', N'/ˈdeɪ.tə ˈen.tri klɑːk/', 5, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (148, 'factory worker', N'/ˈfæk.tər.i ˈwɜː.kər/', 5, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (149, 'reporter', N'/rɪˈpɔːtər/ ', 5, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (150, 'psychologist', N'/saɪˈkɒlədʒɪst/', 5, 3)

        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (151, 'daisy', N'/ˈdeɪzi/', 6, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (152, 'rose', N'/rəʊz/', 6, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (153, 'iris', N'/ˈaɪərɪs/', 6, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (154, 'orchid', N'/ˈɔːkɪd/', 6, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (155, 'tulip', N'/ˈtjuːlɪp/', 6, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (156, 'poppy', N'/ˈpɒpi/', 6, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (157, 'pansy', N'/ˈpænzi/', 6, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (158, 'violet', N'/ˈvaɪələt/', 6, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (159, 'lilac', N'/´lailək/', 6, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (160, 'lily', N'/ˈlɪli/', 6, 1)

        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (161, 'narcissus', N'/nɑːrˈsɪsəs/', 6, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (162, 'mimosa', N'/mɪˈmoʊsə/', 6, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (163, 'sunflower', N'/ˈsʌnflaʊər/', 6, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (164, 'cyclamen', N'/ˈsaɪkləmən/', 6, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (165, 'carnation', N'/kɑːˈneɪʃən/', 6, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (166, 'daffodil', N'/ˈdæfədɪl/', 6, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (167, 'hyacinth', N'/ˈhaɪ.ə.sɪnθ/', 6, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (168, 'anemone', N'/əˈnem.ə.ni/', 6, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (169, 'gladiolus', N'/ɡlædiˈoʊləs/', 6, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (170, 'forget-me-not', N'/fɚˈɡet.mi.nɑːt/', 6, 2)

        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (171, 'bougainvillea', N'/buːɡənˈvɪliə/', 6, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (172, 'buttercup', N'/ˈbʌtərkʌp/', 6, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (173, 'cactus flower', N'/ˈkæktəs ˈflaʊər/', 6, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (174, 'chrysanthemum', N'/krɪˈsænθəməm/', 6, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (175, 'cockscomb', N'//ˈkɒkskəʊm/', 6, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (176, 'confederate rose', N'/kənˈfedərət roʊz/', 6, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (177, 'flamboyant', N'/flæmˈbɔɪənt/', 6, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (178, 'honeysuckle', N'//ˈhʌnisʌkl/', 6, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (179, 'morning-glory', N' /ˈmɔːrnɪŋ ˈɡlɔːri/', 6, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (180, 'cherry blossom', N'/ˈtʃeri ˈblɑːsəm/', 6, 3)

        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (181, 'jail', N'/dʒeɪl/', 7, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (182, 'detective', N'/dɪˈtek.tɪv/', 7, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (183, 'suspect', N'/səˈspekt/', 7, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (184, 'handcuffs', N'/ˈhænd.kʌfs/', 7, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (185, 'badge', N'//bædʒ/', 7, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (186, 'police officer', N'/pəˈliːs ˈɒf.ɪ.səʳ/', 7, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (187, 'gun', N'/gʌn/', 7, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (188, 'holster', N'/ˈhəʊl.stəʳ/', 7, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (189, 'nightstick', N'/ˈnaɪt.stɪk/', 7, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (190, 'trail', N'/treil/', 7, 1)

        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (191, 'judge', N'/dʒʌdʒ/', 7, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (192, 'robes', N'/rəʊbs/', 7, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (193, 'gavel', N'/ˈgæv.əl/', 7, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (194, 'witness', N'/ˈwɪt.nəs/', 7, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (195, 'court reporter', N'/kɔːt rɪpɔrtər/', 7, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (196, 'transcript', N'/ˈtræn.skrɪpt/', 7, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (197, 'bench', N'/bentʃ/', 7, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (198, 'jury', N'/ˈdʒʊə.ri/', 7, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (199, 'jury box', N'/ˈdʒʊə.ri bɒks/', 7, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (200, 'court officer', N'/kɔːt ˈɒf.ɪ.səʳ/', 7, 2)

        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (201, 'witness stand', N'/ˈwɪt.nəs stænd/', 7, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (202, 'prosecuting attorney', N'/ˈprɒs.ɪ.kjuːtɪŋ əˈtɜː.ni/', 7, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (203, 'defense attorney', N'/dɪˈfents əˈtɜː.ni/', 7, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (204, 'defendant', N'/dɪˈfen.dənt/', 7, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (205, 'fingerprint', N'/ˈfɪŋ.gə.prɪnts/', 7, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (206, 'a harsh punishment', N'/ə hɑːrʃˈpʌnɪʃmənt/', 7, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (207, 'a suspended sentence', N'/ə səˈspendɪdˈsentəns/', 7, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (208, 'a wanted notice', N'/əˈwɑːntɪdˈnoʊtɪs/', 7, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (209, 'animal cruelty', N'/ˈænɪmlˈkruːəlti/', 7, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (210, 'attempted murder', N'/əˈtemptɪdˈmɜːrdər/', 7, 3)

        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (211, 'revenue', N'/’revənju:/', 8, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (212, 'treasurer', N'/’treʒərə[r]/', 8, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (213, 'depreciation', N'/di,pri:∫i’ei∫n/', 8, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (214, 'surplus', N'’sə:pləs/', 8, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (215, 'share', N'/∫eə[r]/', 8, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (216, 'records', N'/’rekɔ:d/', 8, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (217, 'turnover', N'/’tɜ:n,əʊvə/', 8, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (218, 'inflation', N'/in’flei∫n/', 8, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (219, 'speculation', N'/,spekjʊ’lei∫n/', 8, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (220, 'sell', N'/sel/', 8, 1)

        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (221, 'speculator', N'/’spekjʊleitə[r]/', 8, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (222, 'foreign currency', N'/’fɒrən ’kʌrənsi/', 8, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (223, 'billing cost', N'/ˈbɪlɪŋ/ /kɒst/', 8, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (224, 'custom barrier', N'/’kʌstəmz/  /bæriə[r]/', 8, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (225, 'joint venture', N'/dʒɔint/ /’vent∫ə[r]/', 8, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (226, 'earnest money', N'/’ɜ:nist/ /’mʌni/', 8, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (227, 'administrative cost', N'əd’ministrətiv/ /kɒst/', 8, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (228, 'price_boom', N'/prais/_ /bu:m/', 8, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (229, 'financial policies', N'/fai’næn∫l/ /’pɒləsi/', 8, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (230, 'account holder', N'/ə’kaʊnt/ /’həʊldə[r]/', 8, 2)

        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (231, 'capital accumulation', N'/kæpitl/ /ə,kju:mjʊ’lei∫n/', 8, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (232, 'confiscation', N'/,kɒnfi’skei∫n/', 8, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (233, 'holding company', N'/’həʊldiη/ /’kʌmpəni/', 8, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (234, 'customs barrier', N'/’kʌstəmz/ /bæriə[r]/', 8, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (235, 'regular payment', N'/’regjulə[r]/ /’peimənt/', 8, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (236, 'financial year', N'/fai’næn∫l/ /jie(r)/', 8, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (237, 'financial policy', N'/fai’næn∫l/ /’pɒləsi/', 8, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (238, 'economic cooperation', N'/,i:kə’nɒmik/ /koʊˌɑːpəˈreɪʃən/', 8, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (239, 'earnest money', N'/’ɜ:nist/ /’mʌni/', 8, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (240, 'certificate import', N'/sə’tifikit/ /im´pɔ:t/', 8, 3)

        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (241, 'venus', N'/’vi:nɘs/', 9, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (242, 'comet', N'/’kɒmɪt/', 9, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (243, 'mercury', N'/’mɜ:kjɘri/', 9, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (244, 'earth', N'/ɜ:θ/', 9, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (245, 'pluto', N'/’plu:tɘʊ/', 9, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (246, 'saturn', N'/’sætɘn/', 9, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (247, 'asteroid', N'/’æstərɔɪd/', 9, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (248, 'mars', N'/mɑ:z/', 9, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (249, 'neptune', N'/’neptju:n/', 9, 1)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (250, 'star', N'/stɑ:/', 9, 1)

        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (251, 'uranus', N'/’jʊɘrɘnɘs/', 9, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (252, 'jupiter', N'/’dʒu:pɪtɘr/', 9, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (253, 'milky way', N'/’milki wei/', 9, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (254, 'constellation', N'/,kɔnstə’leiʃn/', 9, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (255, 'unidentified flying objects (UFOs)', N'/’ʌnai’dentifaid ´flaiiη ‘ɔbdʤikt/', 9, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (256, 'solar eclipse', N'/ˈsəʊ.ləʳ ɪˈklɪps/', 9, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (257, 'lunar eclipse', N'/ˈluː.nəʳ ɪˈklɪps/', 9, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (258, 'atmospheric', N'/,ætməs’ferik/', 9, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (259, 'gravitational', N'/¸grævi´teiʃənəl/', 9, 2)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (260, 'hypothesis', N'/haɪˈpɒθɪ̈sɪs/', 9, 2)

        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (261, 'intergalactic', N'/¸intəgə´læktik/', 9, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (262, 'prerequisite', N'/pri:´rekwizit/', 9, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (263, 'radioactive', N'/¸reidiou´æktiv/', 9, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (264, 'spectroscopy', N'/spek’trɔskəpi/', 9, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (265, 'superficial', N'/ˌsupərˈfɪʃəl/', 9, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (266, 'telescope', N'/’teliskəʊp/', 9, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (267, 'transmutation', N'/¸trænzmju:´teiʃən/', 9, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (268, 'vacuum', N'/’vækjuəm/', 9, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (269, 'satellite', N'/‘sætəlait/', 9, 3)
        INSERT INTO [EnglishApp1].[Word]([Id], [Vocabulary], [Spell], [TopicId], [LevelId]) VALUES (270, 'microscope ', N'/ˈmaɪkrəˌskoʊp/', 9, 3)

END
GO

COMMIT TRANSACTION;

SET IDENTITY_INSERT [EnglishApp1].[Word] OFF;